export const customData = [
    {"Country":"Australia (AU)","Asset":"API panel data","Data type":"Panel/Universe","LGY load status":"Other initiative - Yet to start","GDM load status":"Other initiative - Yet to start","Legal approval":"Yes"},
    {"Country":"Australia (AU)","Asset":"AURemotenessCategories","Data type":"Bridge","LGY load status":"ACOE - In production","LGY Target DB":"<env>_au9","GDM load status":"Not applicable","Legal approval":"Not yet requested"},
    {"Country":"Australia (AU)","Asset":"Channel Dynamics - Local and Global","Data type":"Channel Dynamics","LGY load status":"BDFA - In production","LGY Target DB":"<env>_au9_lgy_cds","GDM load status":"BDFA - In production","Legal approval":"Yes"},
    {"Country":"Australia (AU)","Asset":"Consumer Health - Non Nostra","Data type":"Sell-in/Sell-out/Stock","LGY load status":"BDFA - Yet to start","GDM load status":"Other initiative - In production","Legal approval":"Yes"},
    {"Country":"Australia (AU)","Asset":"Molecule - All 5 files","Data type":"Reference","LGY load status":"BDFA - In production","LGY Target DB":"<env>_au9_lgy","GDM load status":"BDFA - In production","Legal approval":"Yes"},
    {"Country":"Australia (AU)","Asset":"CPI and associated chron files","Data type":"Reference","LGY load status":"BDFA - In production","LGY Target DB":"<env>_au9_lgy_cpi","GDM load status":"BDFA - In production","Legal approval":"Yes"},
    {"Country":"Australia (AU)","Asset":"DDD - Sell-in: Retail and Hospital","Data type":"Sell-in/Sell-out/Stock","LGY load status":"BDFA - Yet to start","GDM load status":"Other initiative - In production","Legal approval":"Yes"},
    {"Country":"Australia (AU)","Asset":"LPD GP EMR","Data type":"EMR","LGY load status":"BDFA - Yet to start","Legal approval":"Yes"},
    {"Country":"Australia (AU)","Asset":"LRx Reference and Linkage (Geography, Patient, Physician, etc.)","Data type":"Reference","LGY load status":"BDFA - Yet to start","Legal approval":"Requested and pending"},
    {"Country":"Australia (AU)","Asset":"MIDAS International Attributes","Data type":"Reference","LGY load status":"BDFA - In production","LGY Target DB":"<env>_au9_lgy_cpi","GDM load status":"BDFA - In production","Legal approval":"Yes"},
    {"Country":"Australia (AU)","Asset":"OneKey","Data type":"Reference","LGY load status":"BDFA - In production","LGY Target DB":"<env>_au9_lgy_oky","GDM load status":"ACOE - In production","Legal approval":"Yes"},
    {"Country":"Australia (AU)","Asset":"Outlet Master (Hospital and Pharmacy)","Data type":"Reference","LGY load status":"BDFA - In production","LGY Target DB":"<env>_au9_lgy","GDM load status":"ACOE - In production","Legal approval":"Yes"},
    {"Country":"Australia (AU)","Asset":"Point of Dispense (Nostra POD) - LRx","Data type":"LRx","LGY load status":"BDFA - Yet to start","Legal approval":"No"},
    {"Country":"Australia (AU)","Asset":"Point of Purchase (Nostra POP)","Data type":"Sell-in/Sell-out/Stock","LGY load status":"BDFA - Yet to start","GDM load status":"Other initiative - Yet to start","Legal approval":"Requested and pending"},
    {"Country":"Australia (AU)","Asset":"Point of Sales (Nostra POS)","Data type":"Sell-in/Sell-out/Stock","LGY load status":"BDFA - Yet to start","GDM load status":"Other initiative - In production","Legal approval":"Requested and pending"},
    {"Country":"Australia (AU)","Asset":"SBPDS Medical","Data type":"Medical","LGY load status":"BDFA - Yet to start","Legal approval":"Yes"},
    {"Country":"Australia (AU)","Asset":"Stock (Nostra Stock)","Data type":"Sell-in/Sell-out/Stock","LGY load status":"BDFA - Yet to start","GDM load status":"Other initiative - Yet to start","Legal approval":"Requested and pending"},
    {"Country":"United Kingdom (GB)","Asset":"Channel Dynamics - Local and Global","Data type":"Channel Dynamics","LGY load status":"BDFA - In production","LGY Target DB":"<env>_gb9_lgy_cds","GDM load status":"BDFA - In production","Legal approval":"Requested and pending"},
    {"Country":"United Kingdom (GB)","Asset":"CPI and associated chron files","Data type":"Reference","LGY load status":"BDFA - In production","LGY Target DB":"<env>_gb9_lgy_cpi","GDM load status":"BDFA - In production","Legal approval":"Requested and pending"},
    {"Country":"United Kingdom (GB)","Asset":"EMR (Vision, EMIS)","Data type":"EMR","LGY load status":"BDFA - Yet to start","Legal approval":"Requested and pending"},
    {"Country":"United Kingdom (GB)","Asset":"HPA – Hospital","Data type":"Hospital","LGY load status":"Other initiative - In production","LGY Target DB":"<env>_df3_gb9","Legal approval":"Yes"},
    {"Country":"United Kingdom (GB)","Asset":"HTI","Data type":"Transactional - Other","LGY load status":"BDFA - Yet to start","Legal approval":"Requested and pending"},
    {"Country":"United Kingdom (GB)","Asset":"LRx","Data type":"LRx","LGY load status":"Other initiative - In production","LGY Target DB":"<env>_df3_gb9","GDM load status":"BDFA - In production","Legal approval":"Requested and pending"},
    {"Country":"United Kingdom (GB)","Asset":"LRx Reference and Linkage (Geography, Patient, Physician, etc.)","Data type":"Reference","LGY load status":"BDFA - In production","LGY Target DB":"<env>_df3_gb9","GDM load status":"BDFA - In production","Legal approval":"Requested and pending"},
    {"Country":"United Kingdom (GB)","Asset":"MIDAS International Attributes","Data type":"Reference","LGY load status":"BDFA - In production","LGY Target DB":"<env>_gb9_lgy_cpi","GDM load status":"BDFA - In production","Legal approval":"Yes"},
    {"Country":"United Kingdom (GB)","Asset":"Molecule - All 5 files","Data type":"Reference","LGY load status":"BDFA - In production","LGY Target DB":"<env>_gb9_lgy_mlc","GDM load status":"BDFA - In production","Legal approval":"Requested and pending"},
    {"Country":"United Kingdom (GB)","Asset":"NHS","Data type":"Transactional - Other","LGY load status":"Other initiative - In production","LGY Target DB":"<env>_gb9","Legal approval":"Requested and pending"},
    {"Country":"United Kingdom (GB)","Asset":"Oncology Cross-sectional Survey","Data type":"Transactional - Other","LGY load status":"BDFA - Yet to start","Legal approval":"Not yet requested"},
    {"Country":"United Kingdom (GB)","Asset":"OneKey","Data type":"Reference","LGY load status":"BDFA - Yet to start","Legal approval":"Requested and pending"},
    {"Country":"United Kingdom (GB)","Asset":"PBS","Data type":"Sell-in/Sell-out/Stock","LGY load status":"BDFA - Yet to start","Legal approval":"Yes"},
    {"Country":"United Kingdom (GB)","Asset":"SBPDS Medical","Data type":"Medical","LGY load status":"BDFA - Yet to start","Legal approval":"Requested and pending"},
    {"Country":"United Kingdom (GB)","Asset":"Sell-in","Data type":"Sell-in/Sell-out/Stock","LGY load status":"Other initiative - In production","LGY Target DB":"<env>_DF3_GB9","Legal approval":"Requested and pending"},
    {"Country":"United Kingdom (GB)","Asset":"Therapy Area - Multipe therapy areas","Data type":"Transactional - Other","LGY load status":"BDFA - Yet to start","Legal approval":"Not yet requested"},
    {"Country":"United Kingdom (GB)","Asset":"Therapy Area - Opthalmology EMR","Data type":"EMR","LGY load status":"BDFA - Yet to start","Legal approval":"Not yet requested"},
    {"Country":"United Kingdom (GB)","Asset":"UK_bridge.csv","Data type":"Bridge","LGY load status":"BDFA - In production","LGY Target DB":"<env>_gb9","GDM load status":"Not applicable","Legal approval":"Not yet requested"},
    {"Country":"United Kingdom (GB)","Asset":"Xponent (Rx)","Data type":"Sell-in/Sell-out/Stock","LGY load status":"Other initiative - In production","LGY Target DB":"<env>_df3_gb9","Legal approval":"Requested and pending"},
    {"Country":"United States (US)","Asset":"Channel Dynamics - Global","Data type":"Channel Dynamics","LGY load status":"BDFA - In production","LGY Target DB":"<env>_us9_lgy","GDM load status":"BDFA - In production","Legal approval":"Yes"},
    {"Country":"United States (US)","Asset":"Channel Dynamics - Local","Data type":"Channel Dynamics","LGY load status":"BDFA - In production","LGY Target DB":"<env>_us9_lgy_cds","GDM load status":"BDFA - In production","Legal approval":"Yes"},
    {"Country":"United States (US)","Asset":"CIME cross walks (Experian – consumer, mortality), Kantar OTC, Comcast, Charter Cable, Everyday Health, Web Md","Data type":"Transactional - Other","LGY load status":"BDFA - In production","LGY Target DB":"<env>_us9_lgy_cme","Legal approval":"Yes"},
    {"Country":"United States (US)","Asset":"Consumer Retail Purchasing - OTC/CPG, Lab","Data type":"Transactional - Other","LGY load status":"BDFA - Yet to start","Legal approval":"Not yet requested"},
    {"Country":"United States (US)","Asset":"Data Integrity ( P1)","Data type":"Reference","LGY load status":"BDFA - In production","LGY Target DB":"<env>_us9_lgy_dif_batch","Legal approval":"Yes"},
    {"Country":"United States (US)","Asset":"Data Integrity ( P2a)","Data type":"Reference","LGY load status":"BDFA - In production","LGY Target DB":"<env>_us9_lgy_dif_batch","Legal approval":"Yes"},
    {"Country":"United States (US)","Asset":"Data Integrity ( P2b)","Data type":"Reference","LGY load status":"BDFA - In production","LGY Target DB":"<env>_us9_lgy_dif_batch","Legal approval":"Yes"},
    {"Country":"United States (US)","Asset":"Data Integrity ( P2c)","Data type":"Reference","LGY load status":"BDFA - In production","LGY Target DB":"<env>_us9_lgy_dif_batch","Legal approval":"Yes"},
    {"Country":"United States (US)","Asset":"Data Integrity ( P2d)","Data type":"Reference","LGY load status":"BDFA - In production","LGY Target DB":"<env>_us9_lgy_dif_batch","Legal approval":"Yes"},
    {"Country":"United States (US)","Asset":"Data Integrity ( P3a)","Data type":"Reference","LGY load status":"BDFA - In production","LGY Target DB":"<env>_us9_lgy_dif_batch","Legal approval":"Yes"},
    {"Country":"United States (US)","Asset":"Data Integrity ( P3b)","Data type":"Reference","LGY load status":"BDFA - In production","LGY Target DB":"<env>_us9_lgy_dif_batch","Legal approval":"Yes"},
    {"Country":"United States (US)","Asset":"Data Integrity ( P4)","Data type":"Reference","LGY load status":"BDFA - In production","LGY Target DB":"<env>_us9_lgy_dif_batch","Legal approval":"Yes"},
    {"Country":"United States (US)","Asset":"DDD","Data type":"Sell-in/Sell-out/Stock","LGY load status":"BDFA - In production","LGY Target DB":"<env>_df2_us9_ddd","Legal approval":"Yes"},
    {"Country":"United States (US)","Asset":"DI - Files list 2","Data type":"Unknown","LGY load status":"Out of scope","GDM load status":"Out of scope","Legal approval":"Yes"},
    {"Country":"United States (US)","Asset":"DX Projection","Data type":"Reference","LGY load status":"BDFA - In production","LGY Target DB":"<env>_DF2_US9","Legal approval":"Yes"},
    {"Country":"United States (US)","Asset":"Early Insight                       ","Data type":"Transactional - Other","LGY load status":"BDFA - In production","LGY Target DB":"<env>_us9_lgy_eit_batch","Legal approval":"Yes"},
    {"Country":"United States (US)","Asset":"ION NIM - Cabinet data","Data type":"Transactional - Other","LGY load status":"Other initiative - Yet to start","Legal approval":"Yes"},
    {"Country":"United States (US)","Asset":"LRx - NDWx or other","Data type":"LRx","LGY load status":"BDFA - Yet to start","Legal approval":"Not yet requested"},
    {"Country":"United States (US)","Asset":"MDSA -- US - HSI   (MDSA)                     ","Data type":"Unknown","LGY load status":"BDFA - In production","LGY Target DB":"<env>_us9_hsi","Legal approval":"Yes"},
    {"Country":"United States (US)","Asset":"NDWx – Dx: History Load: 2000-2009","Data type":"Transactional - Other","LGY load status":"BDFA - In production","Legal approval":"Yes"},
    {"Country":"United States (US)","Asset":"NDWx – LRx: History Load: 2000-2009","Data type":"LRx","LGY load status":"BDFA - In production","Legal approval":"Yes"},
    {"Country":"United States (US)","Asset":"NDWx – Patient","Data type":"LRx","LGY load status":"Other initiative - In production","Legal approval":"Yes"},
    {"Country":"United States (US)","Asset":"NDWx – Procedure","Data type":"LRx","LGY load status":"Other initiative - In production","Legal approval":"Requested and pending"},
    {"Country":"United States (US)","Asset":"NDWx – Provider","Data type":"LRx","LGY load status":"Other initiative - In production","Legal approval":"Yes"},
    {"Country":"United States (US)","Asset":"NPA - History Load: 2006-2009","Data type":"Sell-in/Sell-out/Stock","LGY load status":"BDFA - In production","LGY Target DB":"<env>_us9_batch","Legal approval":"Yes"},
    {"Country":"United States (US)","Asset":"NPA - New To Brand","Data type":"Sell-in/Sell-out/Stock","LGY load status":"BDFA - In production","LGY Target DB":"<env>_us9_batch","Legal approval":"Yes"},
    {"Country":"United States (US)","Asset":"NPA MD","Data type":"Sell-in/Sell-out/Stock","LGY load status":"BDFA - In production","LGY Target DB":"<env>_us9_lgy_npa_batch","Legal approval":"Yes"},
    {"Country":"United States (US)","Asset":"NPP","Data type":"Unknown","LGY load status":"BDFA - In production","LGY Target DB":"<env>_us9_lgy_npp_batch","Legal approval":"Yes"},
    {"Country":"United States (US)","Asset":"NSP","Data type":"Unknown","LGY load status":"BDFA - In production","LGY Target DB":"<env>_us9_lgy","Legal approval":"Yes"},
    {"Country":"United States (US)","Asset":"OMI","Data type":"Unknown","LGY load status":"BDFA - In production","LGY Target DB":"<env>_us9_lgy","Legal approval":"Yes"},
    {"Country":"United States (US)","Asset":"Oncology EMR","Data type":"EMR","LGY load status":"BDFA - In production","LGY Target DB":"<env>_us9_lgy_omr","GDM load status":"BDFA - In production","Legal approval":"Yes"},
    {"Country":"United States (US)","Asset":"OneKey - F14","Data type":"Reference","LGY load status":"BDFA - In production","LGY Target DB":"<env>_us9_lgy_oky","Legal approval":"Yes"},
    {"Country":"United States (US)","Asset":"Onekey - ICADM","Data type":"Reference","LGY load status":"BDFA - In production","LGY Target DB":"<env>_us9_lgy_idm","Legal approval":"Yes"},
    {"Country":"United States (US)","Asset":"PEP","Data type":"Unknown","LGY load status":"BDFA - In production","LGY Target DB":"<env>_us9_lgy_pep","Legal approval":"Yes"},
    {"Country":"United States (US)","Asset":"Pharmetrics Plus","Data type":"Transactional - Other","Legal approval":"Not yet requested"},
    {"Country":"United States (US)","Asset":"PRI - Primary Factory – NPA and Xponent","Data type":"Transactional - Other","LGY load status":"Other initiative - In production","LGY Target DB":"<env>_DF2_PRI","Legal approval":"Yes"},
    {"Country":"United States (US)","Asset":"Remit","Data type":"Transactional - Other","LGY load status":"Other initiative - In production","LGY Target DB":"<env>_df2_us9","Legal approval":"Yes"},
    {"Country":"United States (US)","Asset":"Rx reference files","Data type":"Reference","LGY load status":"BDFA - In production","LGY Target DB":"<env>_DF2_US9","GDM load status":"Other initiative - In production","Legal approval":"Yes"},
    {"Country":"United States (US)","Asset":"SBPDS Medical (NDTI)","Data type":"Medical","LGY load status":"BDFA - In production","Legal approval":"Requested and pending"},
    {"Country":"United States (US)","Asset":"Therapy Area - Oncology EMR","Data type":"EMR","LGY load status":"BDFA - Yet to start","Legal approval":"Not yet requested"},
    {"Country":"United States (US)","Asset":"XPO PD","Data type":"Transactional - Other","LGY load status":"BDFA - In production","LGY Target DB":"<env>_us9_lgy_xpo_batch","Legal approval":"Yes"},
    {"Country":"United States (US)","Asset":"Xponent - Historical data 2006-2009","Data type":"Sell-in/Sell-out/Stock","LGY load status":"BDFA - In production","Legal approval":"Yes"},
    
    ]